# Generated by Django 3.1.5 on 2021-01-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance_management_system', '0002_auto_20210122_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='student_attendance_management_system.attendance'),
        ),
    ]
