# Generated by Django 3.1.5 on 2021-01-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance_management_system', '0003_attendance_attendancereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancereport',
            old_name='student_id',
            new_name='student',
        ),
    ]
